### ISSUE TITLE
THIS MOD SUCKS.

### ISSUE THREAD

**Issue by SuperMonkeyRules** [ChiefArug/complete-compost#1]
THIS MOD SUCKS.

I ADDED IT TO JOEY'S WORLD THINKING IT WOULD MAKE OUR FARMS QUICKER, BUT IT WAS SO UNINTUITIVE THAT I COULDNT EVEN MAKE THE MOD WORK. HOW DOES COMPOZT EVEN FUNCTION? DID YOU EVEN RESEARCH? I PUT A BLOCK IN THE SMELTER TO GET RID OF THE BUGS AND IT DIDNT WORK!
   MY DAD WORKS AT MICROSOFT AND HE WILL GET YOU AND YOUR FAMILY BA NNED FROM EVER USING BING!
PLS ADD TUTORIALE.

K THX BY

**Comment by ChiefArug** [comment]
`git gud`
